Feature/app setup
mbenfowler/bird-alert pull request #1
Opened 2023-08-03 16:15 UTC by mbenfowler

## What this PR does / Testing notes
- Add main view `/` that shows birds in user's area
  - currently just a mocked set of bird codes, but a live fetch for those individual bird deets
- Each bird in this view can be selected with its respective checkbox
- When click on the bird button in the nav bar, you navigate to the `/saved` route
  - This displays just the birds that have been checked in the main view
  - A user may remove a bird from the watch list here as well
- Any invalid url will fallback to the `EmptyState` fallback (no content yet there yet)

### Notes
- I couldn't figure a way to `await` the results of `getBirdsData()` so I had to put an ugly `setTimeout` for the data to actually be in state... is there a better way to do this??
- Only styled for mobile so far

2023-08-03 16:41 UTC, AlexaVanSchaardenburg commented on src/components/App/App.js
> +          <Route path="*" element={<EmptyState />} />
Nice path handling here!

2023-08-04 02:37 UTC, jalbe0076 requested changes
Found a solution to your issue. async functions don't work with forEach loops, that's why you're not getting the data. It's because it does not pause the forEach each time it sees await.

2023-08-04 02:37 UTC, jalbe0076 commented on src/apiCalls.js
> +    });
I read that async functions don't work with forEach loop, try using a for of loop instead, it worked on my end and you can then remove the setTimeout function.

2023-08-04 02:37 UTC, jalbe0076 commented on src/components/App/App.js
> +          } catch (error) {
This setTimeout function can be changed if you update your API call loop

2023-08-04 03:38 UTC, mbenfowler commented on src/apiCalls.js
> +    let birdsData = [];
yep it was totally the `forEach` that was causing this issue! Didn't get a chance to try the reduce, but a `for` loop is allowing me to async it now

2023-08-04 15:45 UTC, merged